version: '2'
messages:
  $i18n: nls/locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  # header: '![](toolchain.svg?localize)'
  # icon: icon.svg
  required:
  - build
  - repo
  info:
    git url: >-
      [https://github.ibm.com/IoT-Enterprise/iotcs-starter](https://github.ibm.com/IoT-Enterprise/iotcs-starter)
    git branch: >-
      [add-headless-toolchain](https://github.ibm.com/IoT-Enterprise/iotcs-starter/tree/add-headless-toolchain)
toolchain:
  name: 'iotcs-starterApp-{{tenant-name}}-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  repo:
    service_id: github_integrated
    parameters:
      repo_url: "https://{{git_access_token}}@github.ibm.com/IoT-Enterprise/iotcs-starter"
      repo_name: "{{toolchain.name}}"
      type: clone
      private_repo: true
      has_issues: true
      enable_traceability: true
      legal: true
  build:
    service_id: pipeline
    parameters:
      services:
      - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          SAMPLE_REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.prod-app-name}}'
          PROD_SPACE_NAME: '{{form.pipeline.parameters.prod-space}}'
          PROD_ORG_NAME: '{{form.pipeline.parameters.prod-organization}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
        execute: true
        services: ["repo"]
    hidden: ["form"]
  deploy:
    service_id: pipeline
    schema:
      $ref: deploy.json
    service-category: pipeline
    parameters:
      app-name: "{{toolchain.name}}-kube-noservices"
      dev-space: "{{space}}"
      dev-organization: "{{organization}}"
      dev-region: "{{region}}"
      api-key: "{{apiKey}}"
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      prod-region: "{{prod-region}}"
      prod-organization: "{{prod-organization}}"
      prod-space: "{{prod-space}}"
      prod-app-name: "{{services.repo.parameters.repo_name}}"
      api-key: "{{apiKey}}"
    schema:
      $ref: deploy.json
